version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  build:
    commands:
      - echo "Building Spring Boot app..."
      - mvn clean package
artifacts:
  files:
    - target/*.jar
